import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";


export const metadata: Metadata = {
  title:{
    default: "Next.js 15 Shopcart",
    template: "%s | Next.js 15 Shopcart",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">
      <main className="flex min-h-screen flex-col">
        <div className="flex-1">
            <Header />
        {children}
        <Footer />
        </div>
      </main>
      </body>
    </html>
  );
}
