import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/landing/header";
import Footer from "@/components/ui/landing/footer";


export const metadata: Metadata = {
  title:{
    default: "Next.js 15 Shopcart",
    template: "%s | Next.js 15 Shopcart",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
